#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

logger = NanoBox::Logvac.new(host: payload[:logvac_host], id: "#{payload[:component][:uid]}.#{payload[:member][:uid]}[update]")

local_md5 = execute "local md5" do
  command "cat /var/nanobox/hooks.md5"
  not_if { ! ::File.exists? "/var/nanobox/hooks.md5" }
end

aws_md5 = execute "aws md5" do
  command "curl -f -k https://s3.amazonaws.com/tools.nanobox.io/hooks/code-stable.md5"
end

if local_md5 != aws_md5
  logger.puts "Updating hooks"
  execute "update hooks" do
    command <<-END
bash -c 'curl \
    -f \
    -k \
    https://s3.amazonaws.com/tools.nanobox.io/hooks/code-stable.tgz \
      | tar -xz -C /opt/nanobox/hooks && \
  curl \
    -f \
    -k \
    -o /var/nanobox/hooks.md5 \
    https://s3.amazonaws.com/tools.nanobox.io/hooks/code-stable.md5'
END
  end
end